services:
  - type: web
    name: algogate-backend
    env: python
    rootDir: projects/backend
    buildCommand: "pip install poetry && poetry install"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ALGOD_ADDRESS
        value: https://testnet-api.algonode.cloud
      - key: EENDHAN_APP_ADDRESS
        value: TPXCOJSONCOKFZDP76S2XR5HU4SISWOXUXFWRSOT2HL3V7TYRCZD7BXWYY
      - key: USDC_ASSET_ID
        value: "10458941"
