name: Pull Request validation

on: [pull_request]


jobs:
  Anil_Fireworks-contracts-ci:
    name: Run Anil_Fireworks-contracts validation
    uses: ./.github/workflows/Anil_Fireworks-contracts-ci.yaml

  Anil_Fireworks-frontend-ci:
    name: Run Anil_Fireworks-frontend validation
    uses: ./.github/workflows/Anil_Fireworks-frontend-ci.yaml

